/**
 * Expo app config for the react-native-automotive example.
 *
 * The `react-native-automotive-expo-plugin` runs at `expo prebuild`
 * time and writes:
 *  - iOS Info.plist UIApplicationSceneManifest (CarPlay scene)
 *  - iOS Entitlements (com.apple.developer.carplay-navigation)
 *  - iOS AppDelegate (notifications delegate install)
 *  - Android Manifest uses-permission entries
 *
 * So we never edit ios/Info.plist or AndroidManifest.xml by hand —
 * those directories are gitignored and regenerated by prebuild.
 */
module.exports = {
  expo: {
    name: 'CarPlayExample',
    slug: 'carplay-example',
    version: '1.0.0',
    orientation: 'portrait',
    userInterfaceStyle: 'automatic',
    // icon / splash intentionally omitted — Expo falls back to its
    // default assets. The example is a developer sandbox, not a
    // user-facing app, so polished branding isn't needed.
    ios: {
      bundleIdentifier: 'io.automotive.rn.example',
      supportsTablet: false,
    },
    android: {
      package: 'io.automotive.rn.example',
    },
    plugins: [
      // Pin Kotlin to 1.9.25 so the Compose Compiler shipped with
      // expo-modules-core 2.2.3 matches (Expo SDK 52 default of
      // 1.9.24 is too old, build fails with a compatibility error).
      [
        'expo-build-properties',
        {
          android: { kotlinVersion: '1.9.25' },
        },
      ],
      [
        'react-native-automotive-expo-plugin',
        {
          carPlayCategory: 'navigation',
          androidAutoCategory: 'navigation',
        },
      ],
    ],
  },
};
