/**
 * Expo app config for the react-native-automotive example.
 *
 * The `react-native-automotive-expo-plugin` runs at `expo prebuild`
 * time and writes:
 *  - iOS Info.plist UIApplicationSceneManifest (CarPlay scene)
 *  - iOS Entitlements (com.apple.developer.carplay-navigation)
 *  - iOS AppDelegate (notifications delegate install)
 *  - Android Manifest uses-permission entries
 *
 * So we never edit ios/Info.plist or AndroidManifest.xml by hand —
 * those directories are gitignored and regenerated by prebuild.
 */
module.exports = {
  expo: {
    name: 'CarPlayExample',
    slug: 'carplay-example',
    version: '1.0.0',
    orientation: 'portrait',
    icon: './assets/icon.png',
    userInterfaceStyle: 'automatic',
    splash: {
      image: './assets/splash.png',
      resizeMode: 'contain',
      backgroundColor: '#000000',
    },
    ios: {
      bundleIdentifier: 'io.automotive.rn.example',
      supportsTablet: false,
    },
    android: {
      package: 'io.automotive.rn.example',
    },
    plugins: [
      [
        'react-native-automotive-expo-plugin',
        {
          carPlayCategory: 'navigation',
          androidAutoCategory: 'navigation',
        },
      ],
    ],
  },
};
